name: clean_nepali_calendar_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clean_nepali_calendar:
    path: ../
  flutter:
    sdk: flutter
  nepali_date_picker: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
